version: "3.9"

services:
  # name of the service - app
  app:
    # build the dockerfile inside our directory, . means that
    build:
      context: .
      args:
        - DEV=true
    # port mappings
    ports:
      - "8000:8000"
    # mapping directories into th docker container
    volumes:
      - ./app:/app
    # command to run the service
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # environment
    environment:
      - DB_HOST:db
      - DB_NAME:devdb
      - DB_USER=devuser
      - DB_PASSWORD:changeme
    # depends on
    depends_on:
      - db
  # db service
  db:
    # image
    image: postgres:13-alpine
    # volumes
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # environment
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
# volumes
volumes:
  # dev db
  dev-db-data: 
